name: studyfun_app
description: A fun educational app for students
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.1
  
  # HTTP requests
  http: ^1.1.0
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # UI components
  cupertino_icons: ^1.0.6
  
  # JSON handling
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  # Add custom fonts if needed
  # fonts:
  #   - family: Quicksand
  #     fonts:
  #       - asset: fonts/Quicksand-Regular.ttf
  #       - asset: fonts/Quicksand-Bold.ttf
  #         weight: 700